import fs from 'fs'
import path from 'path'

/**
 * Reads sites/<id>/config.json files from the parent asty-blog-agent-lean repo.
 * The dashboard runs as a child of that repo (at dashboard/), so sites/ is at ../sites.
 */

export type SiteConfig = {
  site_id: string
  site_url: string
  env: { api_key: string }
  languages: string[]
  canonical_lang: string
  categories: string[]
  deepl?: {
    glossary_ids?: Record<string, string>
    formality?: Record<string, string>
  }
  paths: {
    glossary_dir: string
    topic_queue: string
    voice_guide: string
    drafts: string
    published: string
    affiliate_file?: string
  }
  budget?: {
    deepl_chars_per_run?: number
    deepl_chars_monthly?: number
  }
}

// ../sites from the dashboard root; when running, cwd is dashboard/ or the deploy root.
// We probe common locations.
function resolveSitesDir(): string | null {
  const candidates = [
    path.resolve(process.cwd(), '..', 'sites'),           // local dev: dashboard/ sibling of sites/
    path.resolve(process.cwd(), 'sites'),                 // vercel: monorepo-ish
    path.resolve(process.cwd(), '..', '..', 'sites'),     // defensive
  ]
  for (const p of candidates) {
    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) return p
  }
  return null
}

// Fallback configs bundled into the dashboard build. Used when the sibling
// `sites/` directory is not present in the deployment (e.g. on Vercel where
// only dashboard/ is deployed). Mirrors sites/asty-cabin/config.json.
const FALLBACK_SITES: SiteConfig[] = [
  {
    site_id: 'asty-cabin',
    site_url: 'https://asty-cabin-check.vercel.app',
    env: { api_key: 'ASTY_AGENT_API_KEY' },
    languages: ['en', 'ja', 'zh-hans'],
    canonical_lang: 'en',
    categories: [
      'medical', 'beauty', 'food', 'leisure',
      'transport', 'family', 'corporate', 'culture',
    ],
    deepl: {
      glossary_ids: { ja: 'DEEPL_GLOSSARY_JA_ID', 'zh-hans': 'DEEPL_GLOSSARY_ZH_ID' },
      formality: { ja: 'more', 'zh-hans': 'default' },
    },
    paths: {
      glossary_dir: 'glossary',
      topic_queue: 'topics/manual-queue.md',
      voice_guide: 'sites/asty-cabin/VOICE.md',
      drafts: 'content/drafts',
      published: 'content/published',
      affiliate_file: 'affiliate/links.json',
    },
    budget: { deepl_chars_per_run: 40000, deepl_chars_monthly: 450000 },
  },
]

export function listSites(): SiteConfig[] {
  const dir = resolveSitesDir()
  if (!dir) return FALLBACK_SITES
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true }).filter(d => d.isDirectory())
    const result: SiteConfig[] = []
    for (const e of entries) {
      const cfgPath = path.join(dir, e.name, 'config.json')
      if (!fs.existsSync(cfgPath)) continue
      try {
        const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8')) as SiteConfig
        result.push(cfg)
      } catch {
        // skip invalid configs
      }
    }
    if (result.length === 0) return FALLBACK_SITES
    return result.sort((a, b) => a.site_id.localeCompare(b.site_id))
  } catch {
    return FALLBACK_SITES
  }
}

export function getSite(id: string): SiteConfig | null {
  return listSites().find(s => s.site_id === id) ?? null
}

/**
 * Reads the local DeepL usage JSON (if dashboard is deployed alongside agent repo).
 */
export function readDeeplUsage(): { month: string; chars: number; runs: number } | null {
  const candidates = [
    path.resolve(process.cwd(), '..', 'content', '.deepl-usage.json'),
    path.resolve(process.cwd(), 'content', '.deepl-usage.json'),
  ]
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      try { return JSON.parse(fs.readFileSync(p, 'utf8')) }
      catch { return null }
    }
  }
  return null
}

/**
 * Lists weekly reports generated by score-posts.ts.
 * Returns latest first.
 */
export function listReports(): Array<{ name: string; path: string; mtime: number }> {
  const candidates = [
    path.resolve(process.cwd(), '..', 'reports'),
    path.resolve(process.cwd(), 'reports'),
  ]
  for (const dir of candidates) {
    if (fs.existsSync(dir) && fs.statSync(dir).isDirectory()) {
      return fs.readdirSync(dir)
        .filter(f => f.endsWith('.md'))
        .map(f => {
          const full = path.join(dir, f)
          return { name: f, path: full, mtime: fs.statSync(full).mtimeMs }
        })
        .sort((a, b) => b.mtime - a.mtime)
    }
  }
  return []
}
