import fs from 'fs'
import path from 'path'

/**
 * Reads sites/<id>/config.json files from the parent asty-blog-agent-lean repo.
 * The dashboard runs as a child of that repo (at dashboard/), so sites/ is at ../sites.
 */

export type SiteConfig = {
  site_id: string
  site_url: string
  env: { api_key: string }
  languages: string[]
  canonical_lang: string
  categories: string[]
  deepl?: {
    glossary_ids?: Record<string, string>
    formality?: Record<string, string>
  }
  paths: {
    glossary_dir: string
    topic_queue: string
    voice_guide: string
    drafts: string
    published: string
    affiliate_file?: string
  }
  budget?: {
    deepl_chars_per_run?: number
    deepl_chars_monthly?: number
  }
}

// ../sites from the dashboard root; when running, cwd is dashboard/ or the deploy root.
// We probe common locations.
function resolveSitesDir(): string | null {
  const candidates = [
    path.resolve(process.cwd(), '..', 'sites'),           // local dev: dashboard/ sibling of sites/
    path.resolve(process.cwd(), 'sites'),                 // vercel: monorepo-ish
    path.resolve(process.cwd(), '..', '..', 'sites'),     // defensive
  ]
  for (const p of candidates) {
    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) return p
  }
  return null
}

export function listSites(): SiteConfig[] {
  const dir = resolveSitesDir()
  if (!dir) return []
  const entries = fs.readdirSync(dir, { withFileTypes: true }).filter(d => d.isDirectory())
  const result: SiteConfig[] = []
  for (const e of entries) {
    const cfgPath = path.join(dir, e.name, 'config.json')
    if (!fs.existsSync(cfgPath)) continue
    try {
      const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8')) as SiteConfig
      result.push(cfg)
    } catch {
      // skip invalid configs
    }
  }
  return result.sort((a, b) => a.site_id.localeCompare(b.site_id))
}

export function getSite(id: string): SiteConfig | null {
  return listSites().find(s => s.site_id === id) ?? null
}

/**
 * Reads the local DeepL usage JSON (if dashboard is deployed alongside agent repo).
 */
export function readDeeplUsage(): { month: string; chars: number; runs: number } | null {
  const candidates = [
    path.resolve(process.cwd(), '..', 'content', '.deepl-usage.json'),
    path.resolve(process.cwd(), 'content', '.deepl-usage.json'),
  ]
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      try { return JSON.parse(fs.readFileSync(p, 'utf8')) }
      catch { return null }
    }
  }
  return null
}

/**
 * Lists weekly reports generated by score-posts.ts.
 * Returns latest first.
 */
export function listReports(): Array<{ name: string; path: string; mtime: number }> {
  const candidates = [
    path.resolve(process.cwd(), '..', 'reports'),
    path.resolve(process.cwd(), 'reports'),
  ]
  for (const dir of candidates) {
    if (fs.existsSync(dir) && fs.statSync(dir).isDirectory()) {
      return fs.readdirSync(dir)
        .filter(f => f.endsWith('.md'))
        .map(f => {
          const full = path.join(dir, f)
          return { name: f, path: full, mtime: fs.statSync(full).mtimeMs }
        })
        .sort((a, b) => b.mtime - a.mtime)
    }
  }
  return []
}
